# Generated by Django 3.0.3 on 2020-08-18 17:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('csed', '0003_auto_20200818_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='pub_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 8, 18, 17, 40, 6, 656817, tzinfo=utc)),
        ),
    ]
