# Generated by Django 3.0.3 on 2020-08-18 19:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('csed', '0005_auto_20200818_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 18, 19, 5, 59, 726404, tzinfo=utc), verbose_name='video_date'),
            preserve_default=False,
        ),
    ]
