# Generated by Django 3.0.3 on 2020-08-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csed', '0006_video_video_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_date',
            field=models.DateTimeField(default='0000-00-00 00:00:00'),
        ),
    ]
