# Generated by Django 3.0.3 on 2020-08-18 23:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('csed', '0007_auto_20200819_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 18, 23, 51, 48, 750148, tzinfo=utc)),
        ),
    ]
